### PR TITLE
Solving project path bug

### PR DESCRIPTION
**Pull request by feliperfmarques**
Solving bug occurring when project path has white spaces or special characters

### CODE REVIEW

**Comment by emenegro** [comment]
Thanks, @feliperfmarques 😀

**Comment by feliperfmarques** [comment]
You're welcome @emenegro. Do you have a forecast when you will launch the next release with this bugfix?

**Comment by emenegro** [comment]
I'm planning to do it today but I'm having problems with `stepman`. I'll let you know.

**Comment by emenegro** [comment]
@feliperfmarques The bug is already available in Bitrise. Thanks again! 👍

**Comment by feliperfmarques** [comment]
You're welcome. Thanks so much too @emenegro 😀

**Pull request merged**
